language: erlang
otp_release:
   - 17.1
   - 17.0
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y dos2unix
   - git clone https://github.com/elixir-lang/elixir
   - make -C elixir
   - chmod +x travis-path-fix.sh
   - ./travis-path-fix.sh
   - export PATH=`pwd`/elixir/bin:$PATH
   - mix local.hex --force
   - mix deps.get
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: mix test
